In [1]:
import numpy as np

data_t = np.load('w1d0t.npy')

In [2]:
data_t

array([[[2.400e+01, 6.400e+01, 1.220e+02, ..., 2.900e+01, 1.500e+01,
         1.800e+01],
        [5.600e+01, 6.500e+01, 9.200e+01, ..., 4.100e+01, 3.700e+01,
         6.200e+01],
        [1.090e+02, 1.510e+02, 1.870e+02, ..., 1.110e+02, 8.200e+01,
         8.600e+01],
        ...,
        [1.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 2.700e+01,
         0.000e+00],
        [4.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+01, 7.000e+00,
         0.000e+00],
        [0.000e+00, 0.000e+00, 0.000e+00, ..., 2.000e+00, 4.000e+00,
         0.000e+00]],

       [[1.230e+02, 1.280e+02, 1.940e+02, ..., 1.490e+02, 1.850e+02,
         1.780e+02],
        [2.250e+02, 2.090e+02, 2.870e+02, ..., 7.700e+01, 7.400e+01,
         9.900e+01],
        [2.400e+02, 1.450e+02, 1.930e+02, ..., 4.000e+01, 2.700e+01,
         4.000e+01],
        ...,
        [9.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 9.000e+00,
         0.000e+00],
        [5.000e+00, 0.000e+00, 0.000e+00, ..., 2.000e+00, 8.000e+00,
   

In [3]:
data_m = np.load('w1d0m.npy')
data_m

array([[  24.,   64.,  122., ...,   29.,   15.,   18.],
       [  56.,   65.,   92., ...,   41.,   37.,   62.],
       [ 109.,  151.,  187., ...,  111.,   82.,   86.],
       ...,
       [1725., 1414., 1639., ..., 1842., 2033., 1803.],
       [1571., 1373., 1084., ..., 1924., 2061., 1664.],
       [ 891.,  787.,  706., ..., 1142., 1191.,  989.]])

In [4]:
np.argwhere(data_m== 0)

array([[  3,  10],
       [  3,  13],
       [  3,  14],
       ...,
       [385,  17],
       [385,  21],
       [385,  23]])

In [17]:
data_m[np.where(data_m==0)]=np.nan

In [18]:
np.where(data_m==0)

(array([], dtype=int64), array([], dtype=int64))

In [20]:
data_m[ 385,  22]

1.0

In [21]:
import numpy as np
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=10)
imputer.fit_transform(data_m)


array([[  24.,   64.,  122., ...,   29.,   15.,   18.],
       [  56.,   65.,   92., ...,   41.,   37.,   62.],
       [ 109.,  151.,  187., ...,  111.,   82.,   86.],
       ...,
       [1725., 1414., 1639., ..., 1842., 2033., 1803.],
       [1571., 1373., 1084., ..., 1924., 2061., 1664.],
       [ 891.,  787.,  706., ..., 1142., 1191.,  989.]])

In [26]:
data_m[  385,  23]

nan

In [15]:
nan = np.nan
X = [[1, 2, nan], [3, 4, 3], [nan, 6, 5], [8, 8, 7]]
imputer = KNNImputer(n_neighbors=2, weights="uniform")
imputer.fit_transform(X)


array([[1. , 2. , 4. ],
       [3. , 4. , 3. ],
       [5.5, 6. , 5. ],
       [8. , 8. , 7. ]])